//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barber.Repository.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public PriceHistory()
        {
            this.Resource = new HashSet<Resource>();
            this.Resource2Service = new HashSet<Resource2Service>();
        }
    
        public int ID { get; set; }
        public decimal Price { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual ICollection<Resource> Resource { get; set; }
        public virtual ICollection<Resource2Service> Resource2Service { get; set; }
    }
}
