//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barber.Repository.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.Resource2Service = new HashSet<Resource2Service>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CurrentPriceHistoryID { get; set; }
        public string Description { get; set; }
        public double AvailableQuantity { get; set; }
        public double MinQuantity { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual PriceHistory PriceHistory { get; set; }
        public virtual ICollection<Resource2Service> Resource2Service { get; set; }
    }
}
