//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barber.Repository.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Resource2Service = new HashSet<Resource2Service>();
        }
    
        public int ID { get; set; }
        public int VisitID { get; set; }
        public int ServiceTypeID { get; set; }
        public Nullable<System.TimeSpan> SpentTime { get; set; }
        public string Description { get; set; }
        public int IsHidden { get; set; }
    
        public virtual ICollection<Resource2Service> Resource2Service { get; set; }
        public virtual Visit Visit { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
