//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barber.Repository.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public Visit()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int ClientID { get; set; }
        public int IsHidden { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
